appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: a6xIfgoZSEL+LtdWRTtCbcO6FQ3I+rN7jO9T8mu8lQ/o/JWZnAN2NBwmpfw0Goi9leD6OjwDUMzeIRbkqhvF+uUt3uBYHzfmtmWWPbFyzp2D1Pis5qzxPYvhgfD2Zp+KxYCAvehGSQ/CxvwdlNGSHOSzclY+dp5yD/mRg5+L7ch3meXdQ0ke6muY2tzt5YB5FX1nTTI3eztOjGSafv/Murtt+tQFUO5+foPbVefZ1HWp2XXpAF9AeSXLNwymhhCdOFYJRU9dUqgPVd4NsIbKwqASs2aCdsWCS5m5AJ6wuyHJ3iTnS4/4XpPNwJ9gIzKQbIRQlj3ktVaugvSZjiHk3ixF3fdTbx7rWQ5xJlIGsqhd1qFFLROCs7ZSYvIVFBAF1vaCYr8jOBDJMY9jyRxLkGE/KE92LY+2Qc74sfm2MWuKRXkdMYxLYLDEZSz8Q0cO0vQXK7gzonfpdcvwnWm9kK7eQHdhnfFvIHmRlYhQcoRHBD/ziJr8AsFHOHg0KCJsEr3PbYDlZDYHlwjBOhtbkr3iMlBiukoiVCRXKMuZq3XDXYaqXntL2m4syxZ2UkzPJNQ6D5mM8jGk93rpYbAK0ZYJJED6czaoxA4xuA2n+cxbzMv3IFqNkHXw/VCLqCCzE82yx2spCzez8AnOl1NMpmH8swMfcOXgyZuJ3v1VtGk=}
